Repository rhesis-ai/rhesis, pull requests merged in 2025-08, with the labels that each got.

#161 Fix: Prevent Env Loading In Vscode
  .gitignore
  .vscode/settings.json
Labels: Onboarding

#191 Add Document Extractor Endpoint
  apps/backend/src/rhesis/backend/app/routers/services.py
  apps/backend/src/rhesis/backend/app/schemas/services.py
Labels: Endpoints, Integrations

#195 Document Upload with Automatic Metadata Generation
  apps/frontend/src/app/(protected)/tests/new-generated/components/GenerateTestsStepper.tsx
  apps/frontend/src/utils/api-client/interfaces/documents.ts
  apps/frontend/src/utils/api-client/services-client.ts
Labels: Tests (& Generation), Integrations

#201 Fix: Improve UX/UI Test Generation Stepper
  apps/backend/src/rhesis/backend/app/routers/test_set.py
  apps/frontend/src/app/(protected)/tests/new-generated/components/GenerateTestsStepper.tsx
  apps/frontend/src/components/common/BaseTag.tsx
Labels: Tests (& Generation), Integrations

#210 Fix: Update Start Sh Uvicorn
  apps/backend/start.sh
Labels: Components & Infrastructure

#219 Unit Testing Automation
  .codecov.yml
  .github/workflows/backend-test.yml
  infrastructure/config/service-secrets-config.sh.example
  infrastructure/config/service-secrets-create.sh
  tests/backend/conftest.py
  tests/backend/fixtures/test_setup.py
  tests/backend/routes/fixtures/entities/users.py
Labels: Unit Testing

#232 Core Prompt Synthesizer Implementation
  sdk/src/rhesis/sdk/services/extractor.py
  sdk/src/rhesis/sdk/synthesizers/__init__.py
  sdk/src/rhesis/sdk/synthesizers/assets/prompt_synthesizer.md
  sdk/src/rhesis/sdk/synthesizers/base.py
  sdk/src/rhesis/sdk/synthesizers/paraphrasing_synthesizer.py
  sdk/src/rhesis/sdk/synthesizers/prompt_synthesizer.py
  sdk/src/rhesis/sdk/synthesizers/utils.py
  tests/sdk/synthesizers/prompt_synthesizer/test_document_extraction.py
Labels: Tests (& Generation)
